/**
 * Canonical audit action codes. Append new codes at the end; never rename.
 * Each code maps 1:1 with a row in api_audit_log.action.
 */
export type AuditAction =
  | "auth.login_success"
  | "auth.login_failed"
  | "auth.logout"
  | "auth.mfa_enrolled"
  | "auth.mfa_success"
  | "auth.mfa_failed"
  | "auth.recovery_code_used"
  | "nuvemshop.connected"
  | "nuvemshop.disconnected"
  | "nuvemshop.oauth_failed"
  | "nuvemshop.webhook_received"
  | "nuvemshop.webhook_invalid_signature"
  | "lead.created"
  | "lead.updated"
  | "lead.deleted"
  | "lead.moved"
  | "lead.won"
  | "lead.lost"
  | "lead.bulk_action"
  | "contact.created"
  | "contact.updated"
  | "contact.anonymized"
  | "contact.merge_pending"
  | "contact.merged"
  | "lgpd.anonymize_executed"
  | "member.invited"
  | "member.accepted"
  | "member.role_changed"
  | "member.revoked"
  | "token.created"
  | "token.revoked"
  | "profile.updated"
  | "org.updated"
  | "pipeline.config_updated"
  | "mfa.recovery_codes_regenerated"
  | "notification_prefs.changed"
  | "onboarding.welcome_completed"
  | "onboarding.whatsapp_configured"
  | "onboarding.whatsapp_skipped"
  | "onboarding.nuvemshop_skipped"
  | "onboarding.ai_configured"
  | "onboarding.team_invited"
  | "onboarding.completed"
  | "tenant.onboarded"
  | "conversation.created"
  | "conversation.claimed"
  | "conversation.transferred"
  | "conversation.released"
  | "conversation.closed"
  | "conversation.tags_changed"
  | "contact.tags_changed"
  | "lead.tags_changed"
  | "message.sent"
  | "message.received"
  | "contact.blocked"
  | "ai.handoff_triggered"
  | "ai.reactivated_by_agent"
  | "conversation.usable_for_rag_toggled"
  | "rag.conversations_batch_run"
  | "conversations.daily_digest_run"
  | "lgpd.redact_received"
  | "lgpd.data_request_received"
  | "lgpd.store_redact_received"
  | "lgpd.export_generated"
  | "lgpd.export_delivered"
  | "lgpd.export_failed"
  | "lgpd.redact_executed"
  | "lgpd.redact_skipped_already_anonymized"
  | "lgpd.redact_no_local_footprint"
  | "lgpd.redact_completed"
  | "lgpd.redact_failed"
  | "lgpd.tenant_redacted"
  | "lgpd.consent_changed"
  | "lgpd.manually_approved"
  | "webhook.hmac_invalid"
  | "lgpd.sla_alarm_triggered"
  | "lgpd.sla_watcher_run"
  | "platform_admin.inbox_listed"
  | "platform_admin.conversation_viewed"
  | "platform_admin.tenants_listed"
  | "platform_admin.tenant_viewed"
  | "tenant.created_by_platform_admin"
  | "platform_admin.tenant_health_viewed"
  | "platform_admin.impersonate_started"
  | "platform_admin.impersonate_ended"
  | "platform_admin.impersonate_misconfigured"
  | "tenant.suspended"
  | "tenant.reactivated"
  | "platform_admin.audit_listed"
  | "platform_admin.audit_entry_viewed"
  | "platform_admin.lgpd_listed"
  | "platform_admin.lgpd_request_viewed"
  | "platform_admin.incidents_listed"
  | "platform_admin.incident_viewed"
  | "incident.resolved"
  | "platform_admin.usage_viewed"
  | "platform_admin.users_listed"
  | "platform_admin.user_viewed"
  | "platform_admin.platform_admins_listed"
  | "mcp.tool_called"
  | "ai.credential_created"
  | "ai.credential_deleted"
  | "ai.credential_revalidated"
  | "ai_agent.created"
  | "ai_agent.updated"
  | "ai_agent.archived"
  | "ai_agent.duplicated"
  | "ai_agent.paused"
  | "ai_agent.published"
  | "ai_agent.version_created"
  | "ai_agent.version_updated"
  | "ai_agent.tested"
  | "ai_agent.reverted"
  | "ai.dispatcher_run"
  | "ai.pacing_knobs_updated"
  | "ai.inbox_item_status_changed"
  | "ai.flywheel_proposal_applied"
  | "ai.org_memory_published"
  | "ai.org_memory_entry_created"
  | "ai.org_memory_entry_updated"
  | "ai_agent.run_started"
  | "ai_agent.run_completed"
  | "ai_agent.run_failed"
  | "channel.connected"
  | "channel.reconnected"
  // Número removido da Central. metadata.modo distingue "apagado" (linha
  // deletada — nunca teve conversa) de "arquivado" (histórico preservado).
  | "channel.removed"
  // Um número, uma conexão (0104). `duplicado_removido`: o mesmo WhatsApp foi
  // escaneado num segundo cartão e o segundo saiu. `reassumido`: o número que
  // tinha caído voltou no cartão de sempre, em vez de nascer um cartão novo.
  | "channel.duplicado_removido"
  | "channel.reassumido"
  | "authz.denied"
  | "team.role_changed"
  | "leads.bulk_assigned"
  | "attendant.availability_changed"
  | "routing.config_changed"
  | "routing.worker_run"
  | "attendant.heartbeat_swept"
  | "webhook.source_created"
  | "webhook.source_updated"
  | "webhook.source_deleted"
  | "webhook.lead_received"
  | "webhook.inbound_invalid_signature"
  | "automation.rule_created"
  | "automation.rule_updated"
  | "automation.rule_deleted"
  | "automation.rule_executed"
  | "automation.run_resent"
  | "ai.skill_imported"
  | "ai.skill_installed"
  | "ai.skill_uninstalled"
  | "ai.router_created"
  | "ai.router_updated"
  | "ai.router_deleted"
  | "ai.router_members_updated"
  | "followup_flow.created"
  | "followup_flow.updated"
  | "followup_flow.published"
  | "followup_flow.disabled"
  | "followup_flow.rolled_back"
  | "followup.worker_run"
  | "followup.silence_sweep_run"
  | "followup_enrollment.created"
  | "followup_enrollment.cancelled"
  | "template.created"
  | "template.updated"
  | "template.deleted"
  | "saved_audio.created"
  | "saved_audio.updated"
  | "saved_audio.deleted"
  | "auth.signup_requested"
  | "auth.signup_failed"
  | "auth.signup_confirmed"
  | "auth.signup_provision_failed"
  | "auth.email_link_rejected"
  | "auth.password_reset_requested"
  | "auth.password_reset_request_failed"
  | "auth.password_reset_completed"
  | "auth.password_reset_failed"
  | "tenant.created_by_signup"
  | "conversation.snoozed"
  | "conversation.snooze_cancelled"
  | "conversation.snooze_watcher_run"
  | "conversation.note_added"
  | "conversation.note_deleted"
  | "ai.case_replied"
  | "pipeline.agent_mapping_updated"
  | "pipeline.stage_created"
  | "pipeline.stage_updated"
  | "pipeline.stage_archived"
  // Excluir funil é arquivar (a FK dos negócios é RESTRICT), e por isso existe
  // o par: `restored` é o "Desfazer" da tela do Kanban, não uma ação separada.
  | "pipeline.archived"
  | "pipeline.restored"
  | "plan.task_status_changed"
  | "plan.morning_brief_run"
  // Tarefas do time (0101). `task.created` guarda `delegada` no metadata: tarefa
  // para si mesmo é lembrete, tarefa para outro é combinado entre duas pessoas —
  // e é o segundo caso que alguém vai querer reconstituir depois ("quem pediu
  // isso, e quando?").
  | "task.created"
  | "task.updated"
  | "lead.meeting_scheduled"
  // Primeiro toque disparado do funil: mensagem de abertura que o SDR mandou
  // pelo CRM em vez do WhatsApp Web. Distinto de uma mensagem qualquer do
  // inbox porque é o instante em que o lead deixou de ser só uma linha de lista.
  | "lead.first_touch_sent"
  // O grupo do WhatsApp da reunião: rastro de quando um grupo com o CLIENTE
  // dentro passou a existir. `ja_existia` distingue criação de reaproveitamento.
  | "lead.meeting_group_created"
  | "meetings.reminders_run"
  // Sala de Reuniões (0098) — o copiloto do Meet
  | "meeting.started"
  | "meeting.finished"
  // O preparo da reunião marcada: quem marcou "APN montada" e quando. É o único
  // rastro de um item que vive em jsonb (custom_fields.reuniao.checklist) e não
  // tem timeline própria.
  | "meeting.prep_item_toggled"
  // Contraparte do `conversation.closed`: fechar deixava de ser caminho sem
  // volta pela UI.
  | "conversation.reopened"
  /**
   * Ligações do SDR (migration 0100). `call.audio_uploaded` existe separado de
   * `call.logged` porque é ele que registra a entrada de GRAVAÇÃO DE VOZ do
   * lead no sistema — o dado mais sensível que este produto guarda. Quem
   * responde a um pedido de LGPD precisa poder listar "quando um áudio deste
   * titular entrou e por ordem de quem", e o momento do clique em "Ligar" não
   * responde isso: muita tentativa nunca vira áudio.
   */
  | "call.logged"
  | "call.audio_uploaded"
  /**
   * Análise refeita pelo botão da tela (0106). Entra no audit porque é gasto de
   * IA disparado por uma pessoa e repetível: sem a linha, uma ligação
   * reprocessada dez vezes numa tarde não deixaria rastro de quem clicou.
   */
  | "call.reanalyze_requested"
  /**
   * Troca do número de saída da conversa. Fica no audit porque muda por onde a
   * org fala com aquele cliente daí em diante — e do lado dele a mensagem passa
   * a chegar de outro número. Quando alguém perguntar "por que este lead recebeu
   * de um número estranho", é esta linha que responde (metadata guarda de/para).
   */
  | "conversation.channel_session_changed";
